package env

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Writer handles writing secrets to .env files.
type Writer struct {
	OutputPath string
	BackupDir  string
}

// NewWriter creates a new Writer with the given output path.
func NewWriter(outputPath, backupDir string) *Writer {
	return &Writer{
		OutputPath: outputPath,
		BackupDir:  backupDir,
	}
}

// Write writes the provided key-value secrets to the .env file.
// If the file already exists and backup is enabled, a backup is created first.
func (w *Writer) Write(secrets map[string]string) error {
	if _, err := os.Stat(w.OutputPath); err == nil && w.BackupDir != "" {
		if err := w.backup(); err != nil {
			return fmt.Errorf("backup failed: %w", err)
		}
	}

	f, err := os.OpenFile(w.OutputPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("opening output file: %w", err)
	}
	defer f.Close()

	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	fmt.Fprintf(f, "# Generated by vaultpull on %s\n", time.Now().Format(time.RFC3339))
	for _, k := range keys {
		fmt.Fprintf(f, "%s=%s\n", k, quoteValue(secrets[k]))
	}

	return nil
}

// backup copies the existing .env file to the backup directory.
func (w *Writer) backup() error {
	if err := os.MkdirAll(w.BackupDir, 0700); err != nil {
		return err
	}

	data, err := os.ReadFile(w.OutputPath)
	if err != nil {
		return err
	}

	base := filepath.Base(w.OutputPath)
	timestamp := time.Now().Format("20060102T150405")
	backupPath := filepath.Join(w.BackupDir, fmt.Sprintf("%s.%s.bak", base, timestamp))

	return os.WriteFile(backupPath, data, 0600)
}

// quoteValue wraps a value in double quotes if it contains spaces or special characters.
func quoteValue(v string) string {
	if strings.ContainsAny(v, " \t\n#") {
		v = strings.ReplaceAll(v, "\\", "\\\\")
		v = strings.ReplaceAll(v, "\"", "\\\"")
		return "\"" + v + "\""
	}
	return v
}
